apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-deploy
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: login:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector:
    app: login
  ports:
    - protocol: TCP 
      port: 5000
      targetPort: 5000
      nodePort: 30021  
  type: LoadBalancer
